blueprint:
    name: Fenster/Heizung Synchronisation
    domain: automation
    input:
        fenster_sensor:
            name: Fenster Sensor
            description: Dieser Sensor wird die Synchronisation auslösen.
            selector:
                entity:
                    filter:
                        - domain: binary_sensor
                            device_class: window
        Ziel_heizkoerper:
            name: Ziel Heizung
            description: Die Heizung, die synchronisiert werden soll.
            selector:
                entity:
                    domain: climate
        Heizung_einstellung_offen:
            name: Heizung Einstellung offen
            description: Die Heizung wird auf diese Einstellung gesetzt, wenn das Fenster geöffnet ist.
            selector:
                text:
        Heizung_einstellung_geschlossen:
            name: Heizung Einstellung geschlossen
            description: Die Heizung wird auf diese Einstellung gesetzt, wenn das Fenster geschlossen ist.
            selector:
                text:

triggers:
    - platform: state
        entity_id: !input fenster_sensor
actions:
    - choose:
            - conditions:
                    - condition: state
                        entity_id: !input fenster_sensor
                        state: 'on'
                sequence:
                    - service: climate.set_preset_mode
                        data:
                            preset_mode: !input Heizung_einstellung_offen
                        target:
                            entity_id: !input Ziel_heizkoerper
            - conditions:
                    - condition: state
                        entity_id: !input fenster_sensor
                        state: 'off'
                sequence:
                    - service: climate.set_preset_mode
                        data:
                            preset_mode: !input Heizung_einstellung_geschlossen
                        target:
                            entity_id: !input Ziel_heizkoerper
